export const TYPE_ENUM = {
  INPUT: 'INPUT',
  NUMBER: 'NUMBER',
  TEXT_AREA: 'TEXT_AREA',
  PASSWORD: 'PASSWORD',
  SELECT: 'SELECT',
  DATE: 'DATE',
  DATE_RANGE: 'DATE_RANGE',
  TREE_SELECT: 'TREE_SELECT'
}
